libFBC bugfixes
purduesigbots/libblrs pull request #7
Opened 2017-11-10 16:12 UTC by baylessj

Fix indentation issues, compilation issues with `fbcStallDetect` and precompiled binaries, and the computation of the `fbcStallDetect` function.

2017-11-10 16:16 UTC, baylessj commented
@BottomNotch can you confirm that these changes fix the problems you were observing?

2017-11-14 03:22 UTC, BottomNotch requested changes

2017-11-14 03:22 UTC, BottomNotch commented on libfbc/src/fbc.c
>  	if (fbc->output == fbc->neg_deadband || fbc->output == fbc->pos_deadband) {
seems to mostly work, but if output is 0, it will always detect a stall.  adding `|| fbc->output == 0` to this if statement should solve the problem.

2017-11-14 03:29 UTC, BottomNotch commented
it also should be noted that once a stall is detected, the function will return false until count reaches minCount (which is a confusing name) again.

2017-11-14 13:57 UTC, merged